name = "smart-care-sync-api"
main = "worker.js"
compatibility_date = "2026-07-26"

[[d1_databases]]
binding = "SMART_CARE_D1"
database_name = "smart-care-sync"
database_id = "c26f70ae-5efa-4533-9654-e2579b69792f"
